In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
from scipy import stats, interpolate
import matplotlib.dates as mdates

filepath = 'HOT_Bottle_ALOHA.csv'

# Datetimes were importing as confusing strings until I found:  
# https://www.reddit.com/r/learnpython/comments/743l4g/loading_a_csv_into_a_dataframe_with_a_datetime_as/?rdt=36291
aloha = pd.read_csv(filepath, usecols=['time','depth','ph_bottle_hot','SiO4_bottle_hot','psi_bottle_hot'], parse_dates=['time'])

In [2]:
# Set datetime column as index
# Struggled to organize daily values so they could be grouped until I parsed dates (above) and found this:
# https://www.includehelp.com/python/how-to-set-column-as-date-index.aspx
aloha.set_index('time', inplace=True)

#display(aloha)

In [10]:
# Subset data for surface ocean only 
aloha_100 = aloha[(aloha.depth <100)]

# Average data by day
aloha_daily_avg = aloha_100.groupby('time').mean(numeric_only=True)

# Add daily avgs to dataframe
aloha['ph_daily_avg'] = aloha_daily_avg['ph_bottle_hot']
aloha['sio4_daily_avg'] = aloha_daily_avg['SiO4_bottle_hot']
aloha['psi_daily_avg'] = aloha_daily_avg['psi_bottle_hot']

# Find monthly rolling means and add to dataframe
aloha['ph_monthly_avg'] = aloha['ph_daily_avg'].rolling(window=30, min_periods=3, center=True).mean()
aloha['sio4_monthly_avg'] = aloha['sio4_daily_avg'].rolling(window=30, min_periods=3, center=True).mean()
aloha['psi_monthly_avg'] = aloha['psi_daily_avg'].rolling(window=30, min_periods=3, center=True).mean()

# Find seasonal rolling means (every 3 months) and add to dataframe
aloha['ph_season_avg'] = aloha['ph_daily_avg'].rolling(window=90, min_periods=9, center=True).mean()
aloha['sio4_season_avg'] = aloha['sio4_daily_avg'].rolling(window=90, min_periods=9, center=True).mean()
aloha['psi_season_avg'] = aloha['psi_daily_avg'].rolling(window=90, min_periods=9, center=True).mean()

display(aloha)

,ph_bottle_hot,SiO4_bottle_hot,psi_bottle_hot,depth,ph_daily_avg,sio4_daily_avg,psi_daily_avg,ph_monthly_avg,sio4_monthly_avg,psi_monthly_avg,ph_season_avg,sio4_season_avg,psi_season_avg
time,,,,,,,,,,,,,
1988-10-31 00:00:00+00:00,NaN,0.91,NaN,4.7,NaN,0.852857,NaN,NaN,0.852857,NaN,NaN,0.855860,NaN
1988-10-31 00:00:00+00:00,NaN,1.11,NaN,39.4,NaN,0.852857,NaN,NaN,0.852857,NaN,NaN,0.858733,NaN
1988-10-31 00:00:00+00:00,NaN,1.50,NaN,99.4,NaN,0.852857,NaN,NaN,0.852857,NaN,NaN,0.861483,NaN
1988-10-31 00:00:00+00:00,NaN,2.10,NaN,150.3,NaN,0.852857,NaN,NaN,0.852857,NaN,NaN,0.864119,NaN
1988-10-31 00:00:00+00:00,NaN,2.89,NaN,191.8,NaN,0.852857,NaN,NaN,0.852857,NaN,NaN,0.866647,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,999.9,8.069,NaN,NaN,8.069,NaN,NaN,8.069,NaN,NaN
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,728.7,8.069,NaN,NaN,8.069,NaN,NaN,8.069,NaN,NaN
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,435.5,8.069,NaN,NaN,8.069,NaN,NaN,8.069,NaN,NaN
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,48.9,8.069,NaN,NaN,8.069,NaN,NaN,8.069,NaN,NaN
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,6.0,8.069,NaN,NaN,8.069,NaN,NaN,8.069,NaN,NaN

In [13]:
# Find non-Nan values for plotting

ph_inds = np.where(aloha['ph_season_avg'].notnull())
sio4_inds = np.where(aloha['sio4_season_avg'].notnull())
psi_inds = np.where(aloha['psi_season_avg'].notnull())
display(ph_inds)
display(sio4_inds)
display(psi_inds)

(array([ 6325,  6326,  6327, ..., 98666, 98667, 98668]),)

(array([    0,     1,     2, ..., 98650, 98651, 98652]),)

(array([17065, 17066, 17067, ..., 95061, 95062, 95063]),)

In [9]:
# Plot Rolling Monthly Average shared plots
fig, axs = plt.subplots(figsize=(20,8), nrows=3, sharex=True)
plt.suptitle("Rolling Seasonal Averages")

# pH and Silicate
# Plot pH
ph_0 = axs[0].plot(x_ph_monthly3_100, y_ph_monthly3_100, marker='.', c='turquoise', label='pH')
# Plot Silicate
twinx0 = axs[0].twinx()
sio4_0 = twinx0.plot(x_sio4_monthly3_100, y_sio4_monthly3_100, marker='.', c='magenta', label='Silicate')
axs[0].legend()
# Share legend: https://stackoverflow.com/questions/5484922/secondary-axis-with-twinx-how-to-add-to-legend
lines = ph_0 + sio4_0
labels = [l.get_label() for l in lines]
axs[0].legend(lines, labels, loc=0)


# pH and Silica
# Plot pH
ph_1 = axs[1].plot(x_ph_monthly3_100, y_ph_monthly3_100, marker='.', c='turquoise', label='pH')
# Plot Silica
twinx1 = axs[1].twinx()
psi_1 = twinx1.plot(x_psi_monthly3_100, y_psi_monthly3_100, marker='.', c='orange', label='Silica')
axs[1].legend()
# Share legend
lines = ph_1 + psi_1
labels = [l.get_label() for l in lines]
axs[1].legend(lines, labels, loc=0)

# Silicate and Silica
# Plot silicate
sio4_2 = axs[2].plot(x_sio4_monthly3_100, y_sio4_monthly3_100, marker='.', c='magenta', label='Silicate')
# Plot Silica
twinx2 = axs[2].twinx()
psi_2 = twinx2.plot(x_psi_monthly3_100, y_psi_monthly3_100, marker='.', c='orange', label='Silica')
axs[2].legend()
# Share legend
lines = sio4_2 + psi_2
labels = [l.get_label() for l in lines]
axs[2].legend(lines, labels, loc=0)

,ph_bottle_hot,SiO4_bottle_hot,psi_bottle_hot,depth,ph_daily_avg,sio4_daily_avg,psi_daily_avg,ph_monthly_avg,sio4_monthly_avg,psi_monthly_avg
time,,,,,,,,,,
1988-10-31 00:00:00+00:00,NaN,0.91,NaN,4.7,NaN,0.852857,NaN,NaN,0.852857,NaN
1988-10-31 00:00:00+00:00,NaN,1.11,NaN,39.4,NaN,0.852857,NaN,NaN,0.852857,NaN
1988-10-31 00:00:00+00:00,NaN,1.50,NaN,99.4,NaN,0.852857,NaN,NaN,0.852857,NaN
1988-10-31 00:00:00+00:00,NaN,2.10,NaN,150.3,NaN,0.852857,NaN,NaN,0.852857,NaN
1988-10-31 00:00:00+00:00,NaN,2.89,NaN,191.8,NaN,0.852857,NaN,NaN,0.852857,NaN
...,...,...,...,...,...,...,...,...,...,...
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,999.9,8.069,NaN,NaN,8.069,NaN,NaN
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,728.7,8.069,NaN,NaN,8.069,NaN,NaN
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,435.5,8.069,NaN,NaN,8.069,NaN,NaN
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,48.9,8.069,NaN,NaN,8.069,NaN,NaN
2020-12-20 00:00:00+00:00,NaN,NaN,NaN,6.0,8.069,NaN,NaN,8.069,NaN,NaN